# Generated by Django 5.0.2 on 2024-02-24 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='edu_grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='marital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='state_region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('township', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='employee_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=225, unique=True)),
                ('contract_id', models.CharField(max_length=225)),
                ('finger_id', models.CharField(blank=True, max_length=225, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=225, null=True)),
                ('ssb_id', models.CharField(blank=True, max_length=225, null=True)),
                ('nrc_no', models.CharField(max_length=225, unique=True)),
                ('fathername', models.CharField(max_length=225)),
                ('mothername', models.CharField(max_length=225)),
                ('race', models.CharField(blank=True, max_length=225, null=True)),
                ('religion', models.CharField(blank=True, max_length=225, null=True)),
                ('dob', models.DateField()),
                ('entrydate', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.TextField()),
                ('district', models.CharField(blank=True, max_length=225, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('familytable', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.edu_grade')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gender')),
                ('marital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marital')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.position')),
                ('state_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state_region')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.township')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.type')),
            ],
        ),
        migrations.CreateModel(
            name='education_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=225)),
                ('education_level', models.CharField(max_length=225)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee_profile')),
            ],
        ),
        migrations.CreateModel(
            name='work_exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee_profile')),
            ],
        ),
    ]
