# Generated by Django 5.0.2 on 2024-02-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=225, unique=True)),
                ('contract_id', models.CharField(max_length=225)),
                ('finger_id', models.CharField(max_length=225)),
                ('employee_name', models.CharField(max_length=225)),
                ('ssb_id', models.CharField(max_length=225)),
                ('nrc_no', models.CharField(max_length=225, unique=True)),
                ('fathername', models.CharField(max_length=225)),
                ('mothername', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('race', models.CharField(max_length=225)),
                ('religion', models.CharField(max_length=225)),
                ('dob', models.DateField()),
                ('marital', models.CharField(max_length=225)),
                ('entrydate', models.DateField()),
                ('department', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('education', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('township', models.CharField(max_length=225)),
                ('district', models.CharField(max_length=225)),
                ('state_region', models.CharField(max_length=225)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('familytable', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='state_region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='education_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=225)),
                ('education_level', models.CharField(max_length=225)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee_profile')),
            ],
        ),
        migrations.CreateModel(
            name='township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('township', models.CharField(max_length=225)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state_region')),
            ],
        ),
        migrations.CreateModel(
            name='work_exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee_profile')),
            ],
        ),
    ]
