# Generated by Django 5.0.2 on 2024-02-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='township',
            name='state',
            field=models.CharField(max_length=225),
        ),
    ]
