# Generated by Django 5.0.2 on 2024-02-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_township_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='township',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state_region'),
        ),
    ]
