# Generated by Django 5.0.2 on 2024-04-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employee_attendance_checkout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_gatepass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('emp_code', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(max_length=255)),
                ('status', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
