# Generated by Django 4.1.7 on 2024-09-17 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_emp_gatepass'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_attendance_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_day', models.PositiveIntegerField(default=1)),
                ('ot_hour', models.FloatField(blank=True, default=0.0, null=True)),
                ('absent', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee_profile')),
            ],
        ),
    ]
