# Generated by Django 4.1.7 on 2024-09-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_employee_profile_resign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='contract_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
