# Generated by Django 4.1.7 on 2024-09-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_employee_profile_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='marital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.marital'),
        ),
    ]
