# Generated by Django 4.1.7 on 2024-09-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_employee_profile_marital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.edu_grade'),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='state_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.state_region'),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.township'),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.type'),
        ),
    ]
