# Generated by Django 4.1.7 on 2024-09-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_employee_profile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_attendance_report',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
    ]
